### ISSUE TITLE
Uso inadecuado de markdown

### ISSUE THREAD

**Issue by cosmoscalibur** [EduinHSERNA/Taller-Algebra-Computacional-Alternativo#4]
En el archivo `README.md` las indicaciones de funciones y código en general no se están usando con la forma adecuada de markdown con _backtics_ `` `funcion` ``.

**Comment by cosmoscalibur** [comment]
El uso inadecuado para código también se esta presentando en el notebook.

**Comment by Gia37** [comment]
¿Me podría explicar cómo resolverlo o qué error hay?...recuerdo que en la asesoría dijo que en el notebook el uso de código era permitido para los casos de prueba.

**Comment by cosmoscalibur** [comment]
@Gia37 si observas es una referencia al uso de markdown. En los campos markdown tanto del archivo `README.md` como del notebook, estan indicando instrucciones como texto normal o como negrilla, cuando debe usarse entre _backticks_ tal como lo ilustra el primer comentario de este reporte. Así como en LaTeX existe `\verb` en markdown existen los _backticks_ para el mismo fin.
