### ISSUE TITLE
.gitignore excesivo

### ISSUE THREAD

**Issue by cosmoscalibur** [EduinHSERNA/Taller-Algebra-Computacional-Alternativo#5]
Se presenta un archivo para ignorar extensiones excesivo frente a los requerimientos de este taller. Se presenta la exclusión de directorios para desarrollo local e incluso de módulos solo requeridos en desarrollo web, cuando nada de esto se utiliza en este taller. Una buena práctica de programación es no "inflar" el código más de lo necesario.

**Comment by EduinHSERNA** [comment]
El archivo  .gitignore como lo indica el commit es un archivo inicial, este lo genero por defecto github, ademas como su nombre lo indica el mismo github dice que se ignore. Se realizo varios archivos por decision de los integrantes en que cada  uno realizara los cambios pertinentes en la funciones y luego se integran todos los archivos (funciones) en un solo archivo de python.

**Comment by cosmoscalibur** [comment]
Lo que ignora github es la lista de archivos que se encuentra en la lista de `.gitignore`, no el archivo en si mismo. A lo que se refiere es justamente que dicho archivo contiene las indicaciones para ignorar una cantidad de archivos alta que no se encuentran asociados a archivos que requieran ignorar porque justamente no se van a generar ni usar en el desarrollo. Sin embargo, ya es claro que siendo incial, dicho archivo será depurado para hacer uno consistente con la necesidad del proyecto.
